blog/views/article.py
import os

from flask import Blueprint, render_template, flash, redirect, url_for, request, abort
from flask_login import login_required, current_user

from blog.extensions import db
from blog.forms.text import ReviewForm, ArticleForm
from blog.models.text import Article, ArticleReview


# 长文本（文章）内容蓝图
article = Blueprint('article', __name__)


# 文章列表显示（按时间倒叙）
@article.route('/all', methods=['GET'])
@login_required
def all_articles():
    articles = Article.query.order_by(Article._datetime.desc()).all()
    return render_template('articles.html', articles=articles, user=current_user)


# 发布新文章
@article.route('/new', methods=['GET', 'POST'])
@login_required
def new():
    form = ArticleForm()
    if request.method == 'POST':
        title = form.title.data
        body = form.body.data
        new_article = Article(title=title, body=body, user_id=current_user.id)
        db.session.add(new_article)
        db.session.commit()
        db.session.close()
        flash('Article submitted.')
        return redirect(url_for('article.all_articles'))
    return render_template('new_article.html', user=current_user, form=form)


@article.route('/<int:article_id>', methods=['GET'])
@login_required
def show_article(article_id):
    target_article = Article.query.get(article_id)
    if target_article is None:
        abort(404)

    reviews = target_article.reviews
    rv_count = len(reviews)
    form = ReviewForm()

    return render_template('show_article.html', user=current_user,
                           article=target_article, form=form,
                           reviews=reviews, rv_count=rv_count)


@article.route('/<int:article_id>', methods=['POST'])
@login_required
def review_article(article_id):
    target_article = Article.query.get(article_id)

    # 评论发表和提交
    form = ReviewForm()
    if not form.validate_on_submit():
        flash(form.errors)

    review_body = form.body.data
    review = ArticleReview(body=review_body, user_id=current_user.id, article_id=article_id)
    db.session.add(review)
    db.session.commit()
    db.session.close()
    flash('Review submitted.')
    return redirect(url_for('article.show_article', article_id=article_id))


@article.route('/<int:article_id>/del', methods=['GET'])
@login_required
def delete_article(article_id):
    if Article.query.get(article_id) is None:
        abort(404)
    del_article = Article.query.get(article_id)
    if current_user.id == del_article.user_id:
        if del_article.reviews is not None:
            reviews = del_article.reviews
            for review in reviews:
                db.session.delete(review)
        db.session.delete(del_article)
        db.session.commit()
        db.session.close()
        flash("Article deleted.", 'success')
        return redirect(url_for('article.all_articles'))
    else:
        return redirect(url_for('article.all_articles')), 403


@article.errorhandler(404)
def article_not_found(error):
    if os.path.split(request.path)[-1].isdigit():
        message = {'name': 'Article not found.',
                   'description': 'Please check your access to right article.'}
        return render_template('error.html', error=message)
    else:
        return render_template('error.html', error=error)

blog/views/post.py
import os

from flask import Blueprint, render_template, flash, redirect, url_for, request, abort
from flask_login import login_required, current_user

from blog.extensions import db
from blog.forms.text import PostForm, ReviewForm
from blog.models.text import Post, PostReview

# 短文本蓝图
post = Blueprint('post', __name__)


@post.route('/new', methods=['GET', 'POST'])
@login_required
def new():
    form = PostForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            new_post = Post(body=form.body.data,
                            user_id=current_user.id)
            db.session.add(new_post)
            db.session.commit()
            db.session.close()
            return redirect(url_for('post.all_posts'))

    return render_template('new_post.html',
                           form=form,
                           user=current_user)


# 短文本列表显示（按时间倒序）
@post.route('/all', methods=['GET'])
@login_required
def all_posts():
    posts = Post.query.order_by(Post._datetime.desc()).all()
    return render_template('posts.html',
                           posts=posts,
                           user=current_user)


@post.route('/<int:post_id>', methods=['GET'])
@login_required
def show_post(post_id):
    target_post = Post.query.get(post_id)
    if target_post is None:
        abort(404)
    reviews = target_post.reviews
    rv_count = len(reviews)
    form = ReviewForm()
    return render_template('show_post.html', form=form,
                           post=target_post, user=current_user,
                           reviews=reviews, rv_count=rv_count)


@post.route('/<int:post_id>', methods=['POST'])
@login_required
def review_post(post_id):
    review_form = ReviewForm()

    if review_form.validate_on_submit():
        review_body = review_form.body.data
        new_review = PostReview(body=review_body,
                                user_id=current_user.id,
                                post_id=post_id)
        db.session.add(new_review)
        db.session.commit()
        db.session.close()
        flash('Review submitted.')
        return redirect(url_for('post.show_post', post_id=post_id))


@post.route('/<int:post_id>/edit', methods=['GET'])
@login_required
def edit_post(post_id):
    if Post.query.get(post_id) is None:
        abort(404)

    edit_post = Post.query.get(post_id)
    if current_user.id == edit_post.user_id:
        edit_form = PostForm()
        return render_template('new_post.html',
                               form=edit_form,
                               user=current_user)


@post.route('/<int:post_id>/del', methods=['GET'])
@login_required
def delete_post(post_id):
    if Post.query.get(post_id) is None:
        abort(404)
    del_post = Post.query.get(post_id)
    if current_user.id == del_post.user_id:
        if del_post.reviews is not None:
            reviews = del_post.reviews
            for review in reviews:
                db.session.delete(review)
        db.session.delete(del_post)
        db.session.commit()
        db.session.close()
        flash("Post deleted.", 'success')
        return redirect(url_for('post.all_posts'))
    else:
        return redirect(url_for('post.all_posts')), 403


@post.errorhandler(404)
def post_not_found(error):
    if os.path.split(request.path)[-1].isdigit():
        message = {'name': 'Post not found.',
                   'description': 'Please check your access to right post.'}
        return render_template('error.html', error=message), 404
    else:
        return render_template('error.html', error=error)

blog/templates/articles.html
{% extends "base.html" %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-9">
                <ul class="list-group"></ul>
                    {% for article in articles %}
                    <div class="list-group-item" >
                        <a class='text-dark' href="{{ url_for('article.show_article', article_id=article.id)}}">
                            <h4>{{ article.title }}</h4>
                        </a>

                        <div class="self-text-overflow">{{ article.body | safe}}</div>
                        <div>{{ article.username }}  <small class="text-muted">{{ article.datetime }}</small></div>
                    </div>
                    {% endfor %}
            </div>


            <div class="col-3">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-6 text-center card-text">
                                <a href="/article/new">New Article</a>
                            </div>
                            <div class="col-6 text-center card-text">
                                <a href="/post/new">New Post</a>
                            </div>
                        </div>
                    </div>
                </div>
                <br>
                <div class="card">
                    <div class="card-body">
                        <img src={{user.icon_path}} class="card-img">
                        <h2 class="card-title text-center">{{ user.username }}</h2>
                        <div class="row">
                            <div class="col-6 text-center"><a href="#">Articles</a></div>
                            <div class="col-6 text-center"><a href="#">Posts</a></div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>

{% endblock %}

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>app</title>
    {% endif %}

    {{ bootstrap.load_css() }}
    <link href={{ url_for('static', filename='self-text-overflow.css') }} rel="stylesheet">


</head>
<body class="bg-light">
    {% from 'bootstrap/nav.html' import render_nav_item %}
    {% from 'bootstrap/utils.html' import render_messages %}

    <nav class="navbar navbar-expand-md bg-white navbar-light">
    {% if user %}
        <div class="navbar-nav">
            {{ render_nav_item('main.home', 'Home') }}
            {{ render_nav_item('article.all_articles', 'Articles') }}
            {{ render_nav_item('post.all_posts', 'Posts') }}
            {{ render_nav_item('user.profile', 'Profile') }}
        </div>
        <div class="navbar-nav ml-auto">
            {{ render_nav_item('user.logout', 'Logout') }}
        </div>
    {% else %}
        <div class="navbar-nav">
            {{ render_nav_item('main.home', 'Home') }}
        </div>
    {% endif %}
    </nav>
<br>
    <div class="container">{{ render_messages() }}</div>


    {% block content %}{% endblock %}
    {{ bootstrap.load_js() }}

</body>
</html>

blog/templates/error.html
{% extends "base.html" %}


{% block content %}

<div class="container">
    <div class="card">

        <div class="card-body">
            <h1 class="card-title">{{ error.name }}</h1>
            <p class="card-text">{{ error.description }}</p>
        </div>

    </div>
</div>

{% endblock %}

blog/templates/login.html
<!-- extend from base layout -->
{% extends "base.html" %}

{% block content %}

    <div class="container">
    <div class="card">

        <div class="card-body">
            <h1 class="card-title">Sign In</h1>
            <p class="card-text">
                {% from 'bootstrap/form.html' import render_form %}

                {{ render_form(form, form_type = "basic", button_map = {"login": "primary"}) }}
            </p>
            <a href="/register" class="card-link">Register</a>
        </div>

    </div>
    </div>

{% endblock %}

blog/templates/new_article.html
<!-- extend from base layout -->
{% extends "base.html" %}

{% block content %}
    <div class="container">
    <div class="card">
        <div class="card-body">
            <h1 class="card-title">New Article</h1>
            <p class="card-text">
                {% from 'bootstrap/form.html' import render_form %}

                {{ render_form(form, form_type = "basic", button_map = {"submit": "primary"}) }}
            </p>
        </div>
    </div>
    </div>

    {{ ckeditor.load() }}
    {{ ckeditor.config(name='body', height=500) }}



{% endblock %}

blog/templates/new_post.html
<!-- extend from base layout -->
{% extends "base.html" %}

{% block content %}
    <div class="container">
    <div class="card">
        <div class="card-body">
            <h1 class="card-title">New Post</h1>
            <p class="card-text">
                {% from 'bootstrap/form.html' import render_form %}

                {{ render_form(form, form_type = "basic", button_map = {"submit": "primary"}) }}
            </p>
        </div>
    </div>
    </div>



{% endblock %}

blog/templates/posts.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-9">
                <ul class="list-group">
                    {% for post in posts %}
                        <li class="list-group-item">
                            <div class="media p-3 bg-white">
                                <img class="align-self-top mr-3 rounded-circle" style="width:60px" src={{ post.icon_path }}>
                                <div class="media-body">
                                    <h4>{{ post.username }}</h4>
                                    <a class='text-muted small' href={{ url_for('post.show_post', post_id=post.id) }}>
                                        {{ post.datetime }}
                                    </a>
                                    <p>{{ post.body }}</p>
                                </div>
                            </div>
                        </li>

                    {% endfor %}
                </ul>
            </div>
            <div class="col-3">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-6 text-center card-text">
                                <a href="/article/new">New Article</a>
                            </div>
                            <div class="col-6 text-center card-text">
                                <a href="/post/new">New Post</a>
                            </div>
                        </div>
                    </div>
                </div>
                <br>
                <div class="card">
                    <div class="card-body">
                        <img src={{user.icon_path}} class="card-img">
                        <h2 class="card-title text-center">{{ user.username }}</h2>
                        <div class="row">
                            <div class="col-6 text-center"><a href="#">Articles</a></div>
                            <div class="col-6 text-center"><a href="#">Posts</a></div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

blog/templates/profile.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
    <div class="card">

        <div class="card-body">
            <div class="row">
                <div class="col-3">
                    <a href="profile/icon/upload" data-toggle="modal" data-target="#myModal">
                        <img src={{current_user.icon_path}} class="card-img">
                    </a>
                </div>
                <div class="col-9">
                    <h1 class="card-title">{{ user.username }}</h1>
                    <p class="card-text font-weight-bold">Sex</p>
                    <p class="card-text font-weight-bold">Signature</p>

                </div>
            </div>


        </div>

    </div>
    </div>

    <div class="modal fade" id="myModal">
        <div class="modal-dialog">
            <div class="modal-content">

                <div class="modal-header">
                    <h4 class="modal-title">Upload Icon</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <div class="modal-body">
                    {% from 'bootstrap/form.html' import render_form %}
                    {{ render_form(form, form_type = "basic", button_map = {"submit": "primary"}) }}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

blog/templates/register.html
<!-- extend from base layout -->
{% extends "base.html" %}

{% block content %}

    <div class="container">
        <h1>Register</h1>
        {% from 'bootstrap/form.html' import render_form %}

        {{ render_form(form, form_type = "basic", button_map = {"register": "primary"}) }}
    </div>

{% endblock %}

blog/templates/show_article.html
<!-- extend from base layout -->
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="card">
        <div class="card-body">
            <h1 class="card-title">{{ article.title }}</h1>
            <div class="card-text">{{ article.username }}</div>
            <div class="card-text">
            <p>{{ article.body | safe}}</p></div>
            <div class="card-text text-muted">Created at {{ article.datetime }}</div>
            {% if user.id == article.user_id %}
                <a href={{ url_for('article.delete_article', article_id=article.id) }}>Delete</a>
            {% endif %}
        </div>
    </div>
    <br>


    <div class="card">
        <div class="card-header">
            {% if rv_count <= 1 %}
            {{ rv_count }}  Review
            {% else %}
            {{ rv_count }}  Reviews
            {% endif %}
        </div>
        <div class="card-body">
            {% for review in reviews %}
                <div class="media p-3 bg-white">
                    <img class="align-self-top mr-3" style="width:60px" src={{ review.icon_path }}>
                    <div class="media-body">
                        <h4>{{ review.username }}</h4>
                        <small>{{ review.datetime }}</small>
                        <p>{{ review.body }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            {% from 'bootstrap/form.html' import render_form %}
            {{ render_form(form, form_type = "basic", button_map = {"submit": "primary"}) }}
        </div>
    </div>

</div>
{% endblock %}

blog/templates/show_post.html
<!-- extend from base layout -->
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="card">
        <div class="row card-body">
            <div class="col-1">
                <img class="img-fluid rounded-circle" src={{ post.icon_path }}>
            </div>
            <div class="col-11">
                <h3 class="card-title">{{ post.username }}</h3>
                <p class="card-text">{{ post.body }}</p>
                <p class="card-text text-muted">Created at {{ post.datetime }}</p>
                {% if user.id == post.user_id %}
                    <a href={{ url_for('post.delete_post', post_id=post.id) }}>Delete</a>
                {% endif %}
            </div>

        </div>
    </div>
    <br>
    <div class="card">
        <div class="card-header">
            {% if rv_count <= 1 %}
            {{ rv_count }}  Review
            {% else %}
            {{ rv_count }}  Reviews
            {% endif %}
        </div>
        <div class="card-body">
            {% for review in reviews %}
            <div class="media p-3 bg-white">
                <img class="align-self-top mr-3" style="width:60px" src={{ review.icon_path }}>
                <div class="media-body">
                    <h4>{{ review.username }}</h4>
                    <small>{{ review.datetime }}</small>
                    <p>{{ review.body }}</p>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            {% from 'bootstrap/form.html' import render_form %}
            {{ render_form(form, form_type = "basic", button_map = {"submit": "primary"}) }}
        </div>
    </div>
</div>
{% endblock %}